[package]
name = "egui-directx11"
version = "0.12.1"
edition = "2021"
license = "MIT OR Apache-2.0"

repository = "https://github.com/Nekomaru-PKU/egui-directx11"
authors = ["Nekomaru <Nekomaru@pku.edu.cn>"]

description = "This crate provides a Direct3D11 renderer for `egui`."
categories = ["gui", "game-development"]
keywords = ["gui", "egui", "dx11", "d3d11", "directx11"]

[package.metadata.docs.rs]
targets = ["x86_64-pc-windows-msvc"]

[dependencies]
log = { workspace = true }
egui = { workspace = true }
windows = { workspace = true }
windows-core = { workspace = true }

[dev-dependencies]
egui_demo_lib = { workspace = true }
egui-winit = { workspace = true, default-features = false }
pretty_env_logger = "0.5.0"
winit = { workspace = true, default-features = false }
