[package]
name = "input"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
derive_more = { workspace = true }
tracing = { workspace = true }
scopeguard = { workspace = true }
serde = { workspace = true }
parking_lot = { workspace = true }
windows-core = { workspace = true }
libloading = "0.8"
bitflags = "2.8"

[dependencies.windows]
workspace = true
features = [
    "Foundation",
    "Win32_Graphics_Gdi",
    "Win32_UI_HiDpi",
    "Win32_System_Diagnostics",
    "Win32_System_Diagnostics_Debug",
]
