[package]
name = "dash"
version = "0.1.0"
edition = "2021"
description = "telemetry dashboard"
authors = ["Emily Hudson <emily33901@gmail.com>"]

[dependencies]
anyhow = { workspace = true }
better-panic = "0.3.0"
clap = { workspace = true }
config = "0.15"
crossterm = { version = "0.28", features = ["serde", "event-stream"] }
derive_deref = "1.1.1"
directories = "5.0"
futures = { workspace = true }
human-panic = "2.0"
json5 = "0.4"
lazy_static = "1.5"
libc = "0.2"
log = "0.4"
ratatui = { version = "0.29", features = ["serde", "macros"] }
serde = { workspace = true }
serde_json = { workspace = true }
signal-hook = "0.3"
strip-ansi-escapes = "0.2"
tokio = { workspace = true }
tokio-util = "0.7"
tracing = { workspace = true }
tracing-error = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "serde"] }
telemetry = { path = ".." }
async-trait = { workspace = true }
itertools = "0.14"
