[package]
name = "media"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
derive_more = { workspace = true }
tracing = { workspace = true }
scopeguard = { workspace = true }
serde = { workspace = true }
# openh264 = { path = "../openh264-rs/openh264" }
openh264 = { version = "0.9" }
parking_lot = { workspace = true }
windows-core = { workspace = true }
util = { path = "../util" }
telemetry = { path = "../telemetry" }

[dependencies.windows]
workspace = true
features = [
    "Win32_System_Com_StructuredStorage",
    "Win32_System_Ole",
    "Win32_System_Variant",
]
