[package]
name = "rtc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
async-datachannel = { workspace = true, optional = true }
datachannel = { workspace = true, optional = true }
parking_lot = { workspace = true }
tokio = { workspace = true }
webrtc = { workspace = true }
clap = { workspace = true }
once_cell = { workspace = true }
derive_more = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
telemetry = { path = "../telemetry" }
async-trait = { workspace = true }
tracing = { workspace = true }
bytes = { workspace = true }

[features]
datachannel = ["dep:async-datachannel", "dep:datachannel"]
