[package]
name = "remote-ui"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "remote-ui"
path = "src/main.rs"

[dependencies]
remote = { path = ".." }
media = { path = "../media" }
signal = { path = "../signal" }
rtc = { path = "../rtc" }
anyhow = { workspace = true }
dotenv = { workspace = true }
once_cell = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
eframe = { workspace = true }
egui = { workspace = true }
glow = { workspace = true }
